SET TERMOUT OFF
SET ECHO OFF
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO projetbdd IDENTIFIED BY projetbdd;
ALTER USER projetbdd DEFAULT TABLESPACE USERS;
ALTER USER projetbdd TEMPORARY TABLESPACE TEMP;
CONNECT projetbdd/projetbdd






/*Creation de la table etudiant*/ 
 CREATE TABLE PROJETBDD."ETUDIANT"
   (	"ID_ETUDIANT" NUMBER CONSTRAINT PK_etud PRIMARY KEY,

	PRENOMFR VARCHAR2(20), 
	ADRESSE VARCHAR2(50), 
	CIN NUMBER(8), 
	NOMAR VARCHAR2(20 ), 
	PRENOMAR VARCHAR2(20 ), 
	NOMFR VARCHAR2(20 ), 
	DATENAISS DATE, 
	EMAIL VARCHAR2(50 ),
     NUMTEL NUMBER(8),
	PHOTO BLOB
   );


/*Creation de la table CLASSE*/ 
   CREATE TABLE PROJETBDD.CLASSE 
(
  ID_CLASSE NUMBER NOT NULL 
, GROUPE VARCHAR2(20) 
, NIVEAU VARCHAR2(20) 
, CONSTRAINT CLASSE_PK PRIMARY KEY 
  (
    ID_CLASSE 
  )
  ENABLE 
);




/*Creation de la table EQUIPE */ 
CREATE TABLE PROJETBDD.EQUIPE 
(
  ID_EQUIPE NUMBER NOT NULL 
, NUMEQUIPE VARCHAR2(20) 
, NOTE NUMBER(2)
, ANNÉE NUMBER(4) 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID_EQUIPE 
  )
  ENABLE 
);

/*Creation de la table PROJET */ 
CREATE TABLE PROJETBDD.PROJET 
(
  ID_PROJET NUMBER NOT NULL 
, NOM VARCHAR (150) 
, ANNÉE NUMBER(4) 
, DESCRIPTIONAR  VARCHAR (100)
, DESCRIPTIONFR  VARCHAR (100)
, DESCRIPTIONEN  VARCHAR (100)
, ID_CATEGORIE NUMBER
, ID_ENSEIGNANT NUMBER 
, CONSTRAINT PROJET_PK PRIMARY KEY 
  (
    ID_PROJET 
  )
  
  ENABLE 
);

/*Creation de la table  CATEGORIE */
CREATE TABLE PROJETBDD.CATEGORIE 
(
  ID_CAT NUMBER NOT NULL 
, NOM VARCHAR2(20) 
, DATEC DATE 
, DESCRIPTION VARCHAR2(100) 
, NBREETUDIANT NUMBER
, CONSTRAINT CATEGORIE_PK PRIMARY KEY 
  (
    ID_CAT 
  )
  ENABLE 
);

/*Creation de la table  ENSEIGNANT */
CREATE TABLE PROJETBDD.ENSEIGNANT 
(
  ID_ENSEIGNANT NUMBER NOT NULL 
, EMAIL VARCHAR2(50) 
, PRENOMAR VARCHAR2(20) 
, PRENOMFR VARCHAR(20)
, CIN NUMBER(8) 
, NOMFR VARCHAR2(20) 
, NOMAR VARCHAR2(20) 
, ADRESSE VARCHAR2(50) 
, NUMTEL NUMBER(8) 
, DATENAISS DATE 
 ,ID_DEP NUMBER
, CONSTRAINT ENSEIGNANT_PK PRIMARY KEY 
  (
    ID_ENSEIGNANT 
  )
  ENABLE 
  );
  
/*Creation de la table.ASSOCIATION*/
CREATE TABLE PROJETBDD.ASSOCIATION 
(
  ID_ASSOCIATION NUMBER NOT NULL 
, NOM VARCHAR2(20) 
, ADRESSE VARCHAR2(50) 
, EMAIL VARCHAR2(50) 
, NUMTEL VARCHAR2(20) 
, CONSTRAINT ASSOCIATION_PK PRIMARY KEY 
  (
    ID_ASSOCIATION 
  )
  ENABLE 
);

/*Creation de la table ENTREPRISE*/
CREATE TABLE PROJETBDD.ENTREPRISE 
(
  ID_ENTREPRISE NUMBER NOT NULL 
, NOM VARCHAR2(20) 
, ADRESSE VARCHAR2(50) 
, EMAIL VARCHAR2(50) 
, NUMTEL VARCHAR2(20) 
, CONSTRAINT ENTREPRISE_PK PRIMARY KEY 
  (
    ID_ENTREPRISE 
  )
  ENABLE 
);
/*Creation de la table DEPARTEMENT*/
CREATE TABLE PROJETBDD.DEPARTEMENT 
(
  ID_DEP NUMBER NOT NULL 
, NOM VARCHAR2(20) 
, ABREVIATION VARCHAR2(10) 
, DESCRIPTION VARCHAR2(10) 
, CONSTRAINT DEPARTEMENT_PK PRIMARY KEY 
  (
    ID_DEP 
  )
  ENABLE 
);

/*Creation de la table EST_INSCRIT*/
CREATE TABLE PROJETBDD.EST_INSCRIT 
(
  ID_ETUDIANT NUMBER NOT NULL 
, ID_CLASSE NUMBER NOT NULL 
, ANNÉE NUMBER(4) 
, CONSTRAINT EST_INSCRIT_PK PRIMARY KEY 
  (
    ID_ETUDIANT 
  , ID_CLASSE 
  )
  ENABLE 
);



/*Creation de la table EST_FORMÉE_PAR */

CREATE TABLE PROJETBDD.EST_FORMÉE_PAR 
(
  ID_ETUDIANT NUMBER NOT NULL 
, ID_EQUIPE NUMBER NOT NULL 
, ANNÉE NUMBER(4)
, CONSTRAINT EST_FORMÉE_PAR_PK PRIMARY KEY 
  (
    ID_ETUDIANT 
  , ID_EQUIPE 
  )

  ENABLE 
);



/*Creation de la table EST_DERIGÉE_PAR  */

CREATE TABLE PROJETBDD.EST_DERIGÉE_PAR 
(
  ID_DEP NUMBER NOT NULL 
, ID_ENSEIGNANT NUMBER NOT NULL 
, ANNÉE NUMBER(4) NOT NULL 
, CONSTRAINT EST_DERIGÉE_PAR_PK PRIMARY KEY 
  (
    ID_DEP 
  , ID_ENSEIGNANT 
  , ANNÉE 
  )
  ENABLE 
);



/*Creation de la table EST_EN_PARTENARIAT_AVEC  */
CREATE TABLE PROJETBDD.EST_EN_PARTENARIAT_AVEC 
(
  ID_PROJET NUMBER NOT NULL 
, ID_ASSOCIATION NUMBER NOT NULL 
, CONSTRAINT EST_EN_PARTENARIAT_AVEC_PK PRIMARY KEY 
  (
    ID_PROJET 
  , ID_ASSOCIATION 
  )
  ENABLE 
);


/*Creation de la table  EST_EN_COLLABORATION_AVEC */
CREATE TABLE PROJETBDD.EST_EN_COLLABORATION_AVEC 
(
  ID_PROJET NUMBER NOT NULL 
, ID_ENTREPRISE NUMBER NOT NULL 
, PROPOSÉ NUMBER(1) 
, CONSTRAINT EST_EN_COLLABORATION_AVEC_PK PRIMARY KEY 
  (
    ID_PROJET 
  , ID_ENTREPRISE 
  )
  ENABLE 
);

/*affectation des clées étrangère pour la table projet*/
alter table "PROJETBDD"."PROJET" add constraint FK_ID_CATEGORIE foreign key(ID_CATEGORIE) references CATEGORIE(ID_CAT);
alter table "PROJETBDD"."PROJET" add constraint FK_ID_ENSEIGNABT foreign key(ID_ENSEIGNANT) references ENSEIGNANT(ID_ENSEIGNANT);


/*affectation des clées étrangère pour la table ENSEIGNANT */
alter table PROJETBDD.ENSEIGNANT add constraint endep foreign key(ID_DEP) references DEPARTEMENT(ID_DEP);


/*affectation des clées étrangère pour la table EST_INSCRIT  */
alter table "PROJETBDD"."EST_INSCRIT" add constraint etud foreign key("ID_ETUDIANT") references "ETUDIANT"("ID_ETUDIANT");
alter table "PROJETBDD"."EST_INSCRIT" add constraint classe foreign key("ID_CLASSE") references "CLASSE"("ID_CLASSE");

/*affectation des clées étrangère pour la table EST_EN_PARTENARIAT_AVEC  */
alter table "PROJETBDD"."EST_EN_PARTENARIAT_AVEC" add constraint partenaire_id_projet foreign key("ID_PROJET") references "PROJET"("ID_PROJET");
alter table "PROJETBDD"."EST_EN_PARTENARIAT_AVEC" add constraint partenaire_id_association foreign key("ID_ASSOCIATION") references "ASSOCIATION"("ID_ASSOCIATION");

/*affectation des clées étrangère pour la table EST_EN_COLLABORATION_AVEC  */
alter table "PROJETBDD"."EST_EN_COLLABORATION_AVEC" add constraint collab_projet foreign key("ID_PROJET") references "PROJET"("ID_PROJET");
alter table "PROJETBDD"."EST_EN_COLLABORATION_AVEC" add constraint collab_entreprise foreign key("ID_ENTREPRISE") references "ENTREPRISE"("ID_ENTREPRISE");

/*affectation des clées étrangère pour la table EST_DERIGÉE_PAR   */
alter table "PROJETBDD"."EST_DERIGÉE_PAR" add constraint fk_dep foreign key("ID_DEP") references "DEPARTEMENT"("ID_DEP");
alter table "PROJETBDD"."EST_DERIGÉE_PAR" add constraint enseig foreign key("ID_ENSEIGNANT") references "ENSEIGNANT"("ID_ENSEIGNANT");

/*affectation des clées étrangère pour la table  EST_FORMÉE_PAR  */
alter table "PROJETBDD"."EST_FORMÉE_PAR" add constraint equi foreign key("ID_EQUIPE") references "EQUIPE"("ID_EQUIPE");
alter table "PROJETBDD"."EST_FORMÉE_PAR" add constraint etud_formé foreign key("ID_ETUDIANT") references "ETUDIANT"("ID_ETUDIANT");



